apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: lecocfdh7-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-springboot:b752ee9da370c4709687c8d35a1c46cb540f6ec9@sha256:759b80a626b3009fe35b1ec8b6ef00ed18a0f7bdbe260b91b81a44bb6dc8ea9f
          name: container-image
